apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-delete-task
spec:
  template:
    spec:
      containers:
      - name: task-scheduler
        image: pushkarm029/my-task-scheduler
        command: ["python", "task_scheduler.py", "delete", "{{ .Values.taskId }}"]
      restartPolicy: Never
