apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-read-tasks
spec:
  template:
    spec:
      containers:
      - name: task-scheduler
        image: pushkarm029/my-task-scheduler
        command: ["python", "task_scheduler.py", "read"]
      restartPolicy: Never
