version: '3'

services:
  mysql:
    image: mariadb:11.4-rc-jammy
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - mariadb_network
    ports:
      - 3307:3306

volumes:
  mariadb_volume:

networks:
  mariadb_network:
